/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.assignment.blueoak;

public class LibraryTest {

    // @Test
    // public void testCalculateNumberOfDaysMethod() {

    // Library classUnderTest = new Library();
    // CalculateDays classForMock = mock(CalculateDays.class);
    // when(classForMock.calculateNumberOfDays("05-Feb-2020",
    // "05-Mar-2020")).thenReturn(30L);
    // assertEquals(30, Library.calculateDays());
    // }

}
