/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.assignment.blueoak;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LibraryTest {

  @Test
  public void testMainLibraryMethod() throws Exception {

    assertEquals(80L, 80L);
  }
}
