/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.assignment.blueoak;

import java.util.List;

public class Library {

    public static void main(String[] args) throws Exception {
        calculateDays();
    }

    public static void calculateDays() {

        UserInput userInputObject = new UserInput();
        List<String> startEndDate = userInputObject.userInput();
        System.out.println("Date: " + startEndDate.get(0) + " and " + startEndDate.get(1));

        CalculateDays objectForCalculatingDays = new CalculateDays();

        long numberOfDays = objectForCalculatingDays.calculateNumberOfDays(startEndDate.get(0), startEndDate.get(1));

        if (numberOfDays == -1) {
            System.out.println("Start date should not be later than end date.");

        } else if (numberOfDays == -2) {
            System.out.println("Error while performing operation.");
        } else {
            System.out.println("Number of Days: " + numberOfDays);
        }

    }

}
