/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.assignment.blueoak;

import java.util.List;

public class Library {

    /**
     * @param args
     * @throws Exception
     */
    public static void main(String[] args) throws Exception {

        UserInput userInputObject = new UserInput();
        List<String> startEndDate = userInputObject.userInput();

        CalculateDays objectForCalculatingDays = new CalculateDays();

        long numberOfDays = objectForCalculatingDays.calculateNumberOfDays(startEndDate.get(0), startEndDate.get(1));

        String result = displayResponse(numberOfDays);

        System.out.println(result);
    }

    /**
     * @param numberOfDays
     * @return String
     */
    private static String displayResponse(long numberOfDays) {

        if (numberOfDays == -1) {
            return "Start date should not be later than end date.";

        } else if (numberOfDays == -2) {
            return "Internal error while performing operation.";
        } else if (numberOfDays == -3) {
            return "Please reverify inputs for special character";
        } else {
            return "Number of Days: " + numberOfDays;
        }
    }

}
